import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Providers from "./Providers";
import TelegramWebApp from "@/components/TelegramWebApp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "XBOT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <Providers>
          <Header />
          <TelegramWebApp />
          {children}
        </Providers>
      </body>
    </html>
  );
}
